name: Hercules Insights

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@master
      - name: Hercules Insights
        uses: src-d/hercules@v10.7.2
