name: CI

on: [push]

jobs:
  build:
    runs-on: python:3.7-alpine
    steps:
      - name: Tests
        uses: actions/checkout@v1
      - name: Tests
        run: "pip3 install pipenv && pipenv install && pipenv run pytest"

